apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  jsonData:
    httpMethod: POST
    prometheusType: Prometheus
    prometheusVersion: 2.50.1
    exemplarTraceIdDestinations:
    - datasourceUid: Jaeger
      name: traceID
- name: Jaeger
  type: jaeger
  access: proxy
  url: http://jaeger:16686
