global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'lab'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'lab'
    static_configs:
    - targets: ['172.17.0.1:4242']
