version: "3"
services:
  load-gen:
    image: ellerbrock/alpine-bash-curl-ssl:latest
    command:
    - "/bin/bash"
    - "-c"
    - "sleep 15; while : ; do curl -s -o /dev/null frontend:8765 ; sleep .1; done"
    depends_on:
    - frontend

  frontend: # <1>
    image: public.ecr.aws/mhausenblas/ho11y:stable
    ports:
    - 8765:8765
    environment:
    - "DOWNSTREAM0=http://backend0:8766"
    - "DOWNSTREAM1=http://backend1:8767"
    - "OTEL_RESOURCE_ATTRIB=frontend"
    - "OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317"
    - "HO11Y_INJECT_FAILURE=enabled"
    depends_on:
    - backend0
    - backend1

  backend0:
    image: public.ecr.aws/mhausenblas/ho11y:stable
    ports:
    - 8766:8766
    environment:
    - "HO11Y_PORT=8766"
    - "DOWNSTREAM0=https://mhausenblas.info"
    - "DOWNSTREAM1=https://o11y-in-action.cloud/"
    - "OTEL_RESOURCE_ATTRIB=backend0"
    - "OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317"
    - "HO11Y_INJECT_FAILURE=enabled"
    depends_on:
    - otel-collector

  backend1:
    image: public.ecr.aws/mhausenblas/ho11y:stable
    ports:
    - 8767:8767
    environment:
    - "HO11Y_PORT=8767"
    - "DOWNSTREAM0=https://opentelemetry.io/docs/"
    - "OTEL_RESOURCE_ATTRIB=backend1"
    - "OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317"
    - "HO11Y_INJECT_FAILURE=enabled"
    depends_on:
    - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.55.0
    command: [
      "--config=/conf/otel-collector-config.yaml"
    ]
    volumes:
    - ./otel-config.yaml:/conf/otel-collector-config.yaml
    ports:
    - "4317:4317"
    depends_on:
    - wait-for-ch

  jaeger: # <2>
    image: jaegertracing/all-in-one:1.35
    command: [
      "--grpc-storage-plugin.binary=/etc/jaeger-clickhouse",
      "--grpc-storage-plugin.configuration-file=/etc/clickhouse-plugin.config"
    ]
    volumes:
    - ./jaeger-clickhouse:/etc/jaeger-clickhouse
    - ./clickhouse-plugin.config:/etc/clickhouse-plugin.config
    ports:
    - "9090:9090"
    - "16686:16686"
    - "14250:14250"
    environment:
    - "SPAN_STORAGE_TYPE=grpc-plugin"
    depends_on:
    - wait-for-ch

  wait-for-ch:
    image: ellerbrock/alpine-bash-curl-ssl:latest
    command: "/tmp/setup.sh"
    volumes:
    - ./setup.sh:/tmp/setup.sh
    depends_on:
    - clickhouse

  clickhouse: # <3>
    image: clickhouse/clickhouse-server
    ports:
    - "8123:8123"
    - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
