global:
  scrape_interval: 5s
  external_labels:
   env: "docker"
rule_files: # <1>
- alert.rules
alerting: # <2>
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
scrape_configs: # <3>
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
