version: "3"
services:
  load-gen:
    image: ellerbrock/alpine-bash-curl-ssl:latest
    command:
    - "/bin/bash"
    - "-c"
    - "sleep 5; while : ; do curl -s -o /dev/null http://echo-svc:8888/echo?message=test ; sleep 0.2; done"
    depends_on:
    - echo-svc
  echo-svc:
    build: echo/
    ports:
    - "8888:8888"
    depends_on:
    - otel-col
  otel-col:
    image: otel/opentelemetry-collector-contrib:0.74.0
    command: [
      "--config=/conf/otel-collector-config.yaml"
    ]
    volumes:
    - ./otel-config.yaml:/conf/otel-collector-config.yaml
    ports:
    - "1234:1234"
    - "4317:4317"
    depends_on:
    - prometheus
    - jaeger
  prometheus:
    image: prom/prometheus:v2.33.4
    restart: always
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--enable-feature=exemplar-storage" # <1>
    - "--web.enable-lifecycle"
  jaeger:
    image: jaegertracing/all-in-one:1.43
    ports:
    - "6831:6831/udp"
    - "16686:16686"
    - "14268:14268"
  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    volumes: # <2>
    - ./grafana-storage:/var/lib/grafana
    - ./grafana:/etc/grafana/provisioning
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini

volumes:
  grafana-storage:
