global:
  scrape_interval: 20s
  evaluation_interval: 20s
scrape_configs:
- job_name: "echo-service"
  static_configs:
  - targets: ["echo-svc:8888"]
- job_name: "otel-collector"
  static_configs:
  - targets: ["otel-col:1234"]
storage:
  exemplars:
    max_exemplars: 50000
